name: slash
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  readmore: ^2.2.0
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.3.13

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/


